package:
  name: circexplorer2
  version: "2.1.1"

source:
  fn: CIRCexplorer2-2.1.1.tar.gz
  url: https://pypi.python.org/packages/ec/4a/508fb2a254a3fcc75b9e15f009d071ae42b58754389e53bdbec156d95928/CIRCexplorer2-2.1.1.tar.gz
  md5: 9e300ffea41f42604a51184be4c6bb49

build:
  entry_points:
    - CIRCexplorer2=circ2.command_parse:main
    - fetch_ucsc.py=circ2.fetch_ucsc:main
  number: 0
  skip: True  # [not py27]

requirements:
  build:
    - python
    - pysam >=0.8.4
    - pybedtools
    - docopt
    - scipy
    - tophat
    - cufflinks
    - bedtools
    - ucsc-genepredtogtf
    - ucsc-gtftogenepred
    - ucsc-bedgraphtobigwig
    - ucsc-bedtobigbed

  run:
    - python
    - pysam >=0.8.4
    - pybedtools
    - docopt
    - scipy
    - tophat
    - cufflinks
    - bedtools
    - ucsc-genepredtogtf
    - ucsc-gtftogenepred
    - ucsc-bedgraphtobigwig
    - ucsc-bedtobigbed

test:
  imports:
    - circ2.align
    - circ2.parse
    - circ2.annotate
    - circ2.assemble
    - circ2.denovo

about:
  home: https://github.com/YangLab/CIRCexplorer2
  license: MIT License
  summary: 'Circular RNA analysis toolkits'
