package:
  name: deeptools
  version: '2.3.1'

source:
  fn: deepTools-2.3.1.tar.gz
  url: https://pypi.python.org/packages/20/97/feeca7e55849035bbfd74b3e1631711faa136e46e70182e70ff28980b57d/deepTools-2.3.1.tar.gz
  md5: 8d91349b75ac303b907b4de699c846cb

build:
  number: 0

requirements:
  build:
    - python
    - setuptools
    - numpy >=1.8.0
    - scipy >=0.17.0
    - matplotlib >=1.4.0
    - pysam >=0.8.2
    - gcc
  run:
    - python
    - pybigwig >=0.2.3
    - numpy >=1.8.0
    - scipy >=0.17.0
    - matplotlib >=1.4.0
    - pysam >=0.8.2

test:
  imports:
    - deeptools

  commands:
    - bamCompare --version

about:
  home: https://github.com/fidelram/deepTools
  license: GPL3
  summary: A set of user-friendly tools for normalization and visualzation of deep-sequencing data
