package:
  name: r-stringi
  version: "1.1.1"

source:
  fn: stringi_1.1.1.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/stringi_1.1.1.tar.gz

build:

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r

  run:
    - r

test:
  commands:
    - $R -e "library('stringi')" # [not win]
    - "\"%R%\" -e \"library('stringi')\"" # [win]

about:
  home: http://www.gagolewski.com/software/stringi/
  license: ICU4C (>= 50, optional)
  summary: Character String Processing Facilities.
