about:
  home: 'http://BridgerRNASeq.sourceforge.net'
  license: GPLv2
  summary: 'Bridger is an efficient de novo transcriptome assembler for RNA-Seq data.'

build:
  number: 1
  skip: True # [osx]

requirements:
  build:
    - gcc 
    - zlib
    - boost {{CONDA_BOOST}}*
    - fastool
    - rsem
  run:
    - libgcc
    - zlib
    - boost {{CONDA_BOOST}}*
    - fastool
    - rsem
package:
  name: bridger
  version: 'r2014.12.01'
source:
  #git_url: https://github.com/fmaguire/Bridger_Assembler 
  url: http://tenet.dl.sourceforge.net/project/rnaseqassembly/Bridger_r2014-12-01.tar.gz
  fn: Bridger_r2014-12-01.tar.gz
  md5: 4f4a8a00363df197463259a7eef906b2
test:
  commands:
    - 'Assemble -h 2>&1 | grep "Usage: Assemble"'
